export default {
  STORY_NAME: 'STORY_NAME',
  STORY_ADD: 'STORY_ADD',
  STORY_DELETE: 'STORY_DELETE',
  STORY_UPDATE_PROGRESS: 'STORY_UPDATE_PROGRESS',
  STORY_UPDATE_INDEX: 'STORY_UPDATE_INDEX',
  STORY_UPDATE_INTERVAL_ID: 'STORY_UPDATE_INTERVAL_ID',
  STORY_UPDATE_VIDEO_DURATION: 'STORY_UPDATE_VIDEO_DURATION',
  STORY_PREV: 'STORY_PREV',
  STORY_NEXT: 'STORY_NEXT',
};
